auctions/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing/<int:id>", views.listing, name="listing"),
    path("watchlist",views.watchlist,name="watchlist"),
    path("category/<int:cat_name>",views.category,name="category"),
    path("createListing",views.createListing,name="createListing")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

capstone/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('cookbook.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass
    
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):
    name = models.CharField(max_length=150)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    watchers = models.ManyToManyField(User,related_name="watchlist", blank=True)
    
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="listings")
    imageurl = models.CharField(max_length=600, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    closed = models.BooleanField(default=False)

    description = models.CharField(max_length=600)

    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} by {self.author}"

class Bid(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="biddings")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="biddings")
    price = models.DecimalField(max_digits=6, decimal_places=2)

    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"${self.price} bid on {self.listing.name} by {self.author}"

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=600)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE,related_name="comments")
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment on {self.listing.name} by {self.author}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.timezone import now
from django import forms
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models.query import EmptyQuerySet

from .models import *

class CloseForm(forms.Form):
    closevar = forms.CharField(max_length=7,min_length=0)

class WatchForm(forms.Form):
    watchvar = forms.CharField(max_length=10,min_length=0)

class BidForm(forms.Form):
    price = forms.DecimalField(label="Place Your Bid ", max_digits=6, decimal_places=2)

class CommentForm(forms.Form):
    commentContent = forms.CharField()

class ListingForm(forms.Form):
    name = forms.CharField(max_length=150)
    
    categoryid = forms.CharField(max_length=10)
    imageurl = forms.CharField(max_length=600, required=False)
    price = forms.DecimalField(max_digits=6, decimal_places=2)

    description = forms.CharField(max_length=600)

def groupListings(listings):
    listingGroup = []
    listingGroupTotal = []
    listingCount = 0
    listingGroupCount = 0
    for listing in listings:
        listingGroup.append(listing)
        listingCount += 1
        if listingCount == 3:
            listingGroupTotal.append(listingGroup)
            listingGroup = []
            listingCount = 0
            listingGroupCount += 1
    listingGroupTotal.append(listingGroup)
    return listingGroupTotal

def index(request):
    groupedListings = groupListings(Listing.objects.all().filter(closed=False))

    return render(request, "auctions/index.html",{
        "listingGroupTotal": groupedListings,
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

def listing(request,id):
    error = False
    errorM = ""

    if request.user.is_authenticated:
        curUser = User.objects.get(username=request.user.username)
    curlisting = Listing.objects.get(pk=id)

    if curlisting is None:
        return render(request,"auctions/error.html",{
            "error": "Could not find listing"
        })

    if 'closevar' in request.POST:
        closeform = CloseForm(request.POST)
        if closeform.is_valid():
            closevar = closeform.cleaned_data["closevar"]
            if closevar == "Close":
                curlisting.closed = True
                curlisting.save()
        else:
            return render(request,"auctions/error.html",{
                "error": "Invalid Form"
            })

    if 'watchvar' in request.POST:
        watchform = WatchForm(request.POST)
        if watchform.is_valid():
            watchvar = watchform.cleaned_data["watchvar"]
            if watchvar == "Add":
                #add to watchlist
                curUser.watchlist.add(curlisting)
            else:
                #remove from the watchlist
                #check if remove() works
                curUser.watchlist.remove(curlisting)
        else:
            return render(request,"auctions/error.html",{
                "error": "Invalid Form"
            })

    if 'price' in request.POST:
        #create bid
        bidform = BidForm(request.POST)
        if bidform.is_valid():

            price = bidform.cleaned_data["price"]

            bidlist = curlisting.biddings.all()
            bidhighprice = 0
            if bidlist.exists():
                bidhighprice = bidlist.order_by('price').last().price

            if price < bidhighprice:
                error = True
                errorM = "You must bid higher than the highest bidding"
            else:
                created_date = models.DateTimeField(default=now, editable=False)
                bid = Bid.objects.create(author=curUser, price=price, time=created_date, listing=curlisting)
        
        else:
            return render(request,"auctions/error.html",{
                "error": "Invalid Form"
            })

    if 'commentContent' in request.POST:
        #create comment
        comm_form = CommentForm(request.POST)
        if comm_form.is_valid():
            content = comm_form.cleaned_data["commentContent"]

            created_date = models.DateTimeField(default=now, editable=False)
            comment = Comment.objects.create(author=curUser, content=content, time=created_date, listing=curlisting)
        else:
            return render(request,"auctions/error.html",{
                "error": "Invalid Form"
            })

    #Check for Watchlist
    try:
        watchcheck = curUser.watchlist.get(pk=id)
        watching = True
    except:
        watching = False


    #Load Biddings
    bidlist = curlisting.biddings.all()
    bidhighest = bidlist.order_by('price').last()
    if bidlist.exists():
        bidhighprice = bidlist.order_by('price').last().price
    else:
        bidhighprice = 0

    if curlisting.price > bidhighprice:
        curPrice = curlisting.price
    else:
        curPrice = bidhighprice

    #Load Comments
    comments = curlisting.comments.all()
        
    return render(request, "auctions/listing.html",{
                "listing": curlisting,
                "InWatch": watching,
                "biddings": bidlist,
                "bidhigh": bidhighest,
                "price": curPrice,
                "comments": comments,
                "IsAuthenticated": request.user.is_authenticated,
                "Iserror": error,
                "errorM" : errorM
            })

@login_required
def watchlist(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    currentUser = User.objects.get(username=request.user.username)

    groupedWatchList = groupListings(currentUser.watchlist.all())

    return render(request,"auctions/watchlist.html",{
        "watchingGroupTotal": groupedWatchList
    })

def category(request, cat_name):
    if cat_name == 0:
        groupedListings = groupListings(Listing.objects.all())
        return render(request,"auctions/category.html",{
            "listingGroupTotal": groupedListings,
            "categories": Category.objects.all()
        })
    curcat = Category.objects.get(id=cat_name)
    catList = curcat.listings.all()
    groupedListings = groupListings(catList)
    return render(request,"auctions/category.html",{
        "listingGroupTotal": groupedListings,
        "categories": Category.objects.all()
    })

def createListing(request):
    if request.user.is_authenticated:
        curUser = User.objects.get(username=request.user.username)
    else:
        return HttpResponseRedirect(reverse("login"))

    if request.method == "POST":
        listform = ListingForm(request.POST)
        print("POST received")
        print(listform.errors)
        if listform.is_valid():
            print("Form Valid")
            name = listform.cleaned_data["name"]
            imageurl = listform.cleaned_data["imageurl"]
            description = listform.cleaned_data["description"]
            price = listform.cleaned_data["price"]
            categoryid = listform.cleaned_data["categoryid"]
            category = Category.objects.get(id=categoryid)
            created_date = models.DateTimeField(default=now, editable=False)

            newlisting = Listing(name=name, author=curUser, category=category, imageurl=imageurl, price=price, description=description, time=created_date, closed=False)
            print(newlisting)
            newlisting.save()
            
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request,"auctions/error.html",{
                "error": "Invalid Form"
            })
    return render(request,"auctions/createListing.html",{
        "category": Category.objects.all()
    })

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md sidebar">
            <ul class="list-group">
                <li class="list-group-item"> Categories </li>
                <li class="list-group-item">
                    <a href="{% url 'category' 0 %}">All</a>
                </li>
            {% for section in categories %}
                <li class="list-group-item">
                    <a href="{% url 'category' section.id %}">{{ section }}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
        <div class="col-md">
            <div class="container">
                <div class="row">
                    {% for listings in listingGroupTotal %}
                        {% for listing in listings%}
                        <div class="col-sm">
                            <div class="card h-100" style="width: 18rem;">
                                {% if listing.imageurl != "" %}
                                <img src={{listing.imageurl}} class="card-img-top" alt="..." style="width: 100%;height: 15vw;object-fit: cover;">
                                {% endif %}
                                <div class="card-body">
                                <h5 class="card-title">{{listing.name}}</h5>
                                <p class="card-text">{{ listing.description|truncatechars:20 }}</p>
                                <p class="card-text">${{ listing.price }}</p>
                                <a class="nav-link" href="{% url 'listing' listing.id %}">Purchase</a>
                                
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="w-100"></div>
                    {% endfor %}
                
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

auctions/templates/auctions/createListing.html
{% extends "auctions/layout.html" %}

{% block body %}

    <form action="{% url 'createListing' %}" method="post">

        {% csrf_token %}

        <div class="form-group">
            <label for=pname>Name</label>
            <input id=pname class="form-control" autofocus type="text" name="name" required="" placeholder="Awesome Product">
        </div>

        <div class="form-group">
            <label for=imageid>Image URL</label>
            <input id=imageid class="form-control" autofocus type="text" name="imageurl">
        </div>

        <div class="form-group">
            <label for="id_price">Price</label>
            <input type="number" name="price" step="0.01" required="" id="id_price">
        </div>

        <div class="form-group">
            <label for=des>Description</label>
            <textarea id=des class="form-control" name="description" rows="10" cols="80" placeholder="Write your description here." style="overflow:hidden; height:auto; width:auto"></textarea>
        </div>

        <div class="form-group">
            <label for=categorylabelid>Category</label>
            <select id=categorylabelid class="form-control" name="categoryid">
                {% for cat in category %}
                <option value={{ cat.id }}>{{ cat.name }}</option>
                {% endfor %}
            </select>
        </div>

        <input class="btn btn-primary" type="submit" value="Post Listing">
    </form>
    
{% endblock %}

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>Error</h1>
    <h2>{{ error }}</h2>

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    

    <div class="container">
        <div class="row">
            {% for listings in listingGroupTotal %}
                {% for listing in listings%}
                <div class="col-sm">
                    <div class="card h-100" style="width: 18rem;">
                        {% if listing.imageurl != "" %}
                        <img src={{listing.imageurl}} class="card-img-top" alt="..." style="width: 100%;height: 15vw;object-fit: cover;">
                        {% endif %}
                        <div class="card-body">
                        <h5 class="card-title">{{listing.name}}</h5>
                        <p class="card-text">{{ listing.description|truncatechars:20 }}</p>
                        <p class="card-text">${{ listing.price }}</p>
                        <a class="nav-link" href="{% url 'listing' listing.id %}">Purchase</a>
                        
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="w-100"></div>
            {% endfor %}
        
        </div>
    </div>
        
        
{% endblock %}

auctions/templates/auctions/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        {% load static %}
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'auctions/styles.css' %}">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'category' 0 %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'createListing' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h4>{{listing.name}}
        {% if listing.closed %}
            <span class="badge badge-info">Closed</span>
        {% endif %}
    </h4>

    {% if listing.closed %}
    {% if bidhigh.author == user %}
    <div class="alert alert-success" role="alert">
        You have won this listing!
    </div>
    {% endif %}
    {% endif %}
    
    <p>Time Posted: {{listing.time}}</p>
    <p>By {{listing.author}}</p>

    <img src={{listing.imageurl}}>

    <h1>${{ price }}</h1>

    {% if IsAuthenticated %}
    {% if user == listing.author %}
    {% if listing.closed == False %}
    <form action="{% url 'listing' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="closevar" value="Close">
        <input type="submit" value="Close Listing">
    </form>
    {% endif %}
    {% endif %}
    {% endif %}

    <p>{{listing.description}}</p>

    {% if IsAuthenticated %}
    {% if InWatch %}
    <form action="{% url 'listing' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="watchvar" value="Remove">
        <input type="submit" value="Remove From Watchlist">
    </form>
    {% else %}
    <form action="{% url 'listing' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="watchvar" value="Add">
        <input type="submit" value="Add To Watchlist">
    </form>
    {% endif %}
    {% endif %}

    {% if IsAuthenticated %}
    <div class="form-group">
        <form action="{% url 'listing' listing.id %}" method="post">
        {% csrf_token %}
        <label for="id_price">Place Your Bid :</label>
        <input type="number" name="price" step="0.01" required="" min={{ price }} id="id_price">
        <input type="submit" value="Post Bidding">
        </form>
    </div>
    {% endif %}

    {% if Iserror%}
    <div class="alert alert-danger" role="alert">
        {{ errorM }}
    </div>
    {% endif %}

    <ul class="list-group">
        <li class="list-group-item"> Biddings </li>
    {% for bid in biddings %}
        <li class="list-group-item">{{bid.price}}</li>
    {% endfor %}
    </ul>

    {% if IsAuthenticated %}
    <div class="form-group">
        <form action="{% url 'listing' listing.id %}" method="post">
            {% csrf_token %}
            <textarea class="form-control" name="commentContent" rows="10" cols="80" placeholder="Write your comment here." style="overflow:hidden; height:auto; width:auto"></textarea>
            <input type="submit" value="Post Comment">
        </form>
    </div>  
    {% endif %}

    <ul class="list-group">
        <li class="list-group-item"> Comments </li>
    {% for comment in comments %}
        <li class="list-group-item">
            <h4>{{comment.author}}</h4>
            <p>{{comment.content}}</p>
            <p>{{comment.time}}</p>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>My Watchlist</h2>
    {% for listing in watchlist %}

    {% endfor %}

    <div class="container">
        <div class="row">
            {% for listings in watchingGroupTotal %}
                {% for listing in listings%}
                <div class="col-sm">
                    <div class="card" style="width: 18rem;">
                        {% if listing.imageurl != "" %}
                        <img src={{listing.imageurl}} class="card-img-top" alt="..." style="width: 100%;height: 15vw;object-fit: cover;">
                        {% endif %}
                        <div class="card-body">
                        <h5 class="card-title">{{listing.name}}
                            {% if listing.closed %}
                                <span class="badge badge-info">Closed</span>
                            {% endif %}
                        </h5>
                        <p class="card-text">{{ listing.description|truncatechars:20 }}</p>
                        <p class="card-text">${{ listing.price }}</p>
                        
                        {% if listing.closed %}
                            <a class="nav-link" href="{% url 'listing' listing.id %}">View Detail</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'listing' listing.id %}">Purchase</a>
                        {% endif %}
                        
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="w-100"></div>
            {% endfor %}
        
        </div>
    </div>

    {{request.user.first_name}}

{% endblock %}